<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SizeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sizes = [
            ['product_id' => '1', 'size' => 's'],
            ['product_id' => '2', 'size' => 's'],
            ['product_id' => '3', 'size' => 's'],
            ['product_id' => '4', 'size' => 's'],
            ['product_id' => '5', 'size' => 's'],
            ['product_id' => '6', 'size' => 's'],
            ['product_id' => '7', 'size' => 's'],
            ['product_id' => '8', 'size' => 's'],
            ['product_id' => '9', 'size' => 's'],
            ['product_id' => '11', 'size' => 's'],
            ['product_id' => '11', 'size' => 's'],
            ['product_id' => '12', 'size' => 's'],
            ['product_id' => '13', 'size' => 's'],
            ['product_id' => '14', 'size' => 's'],
            ['product_id' => '15', 'size' => 's'],
            ['product_id' => '16', 'size' => 's'],
            ['product_id' => '17', 'size' => 's'],
            ['product_id' => '18', 'size' => 's'],
            ['product_id' => '19', 'size' => 's'],
            ['product_id' => '20', 'size' => 's'],
            ['product_id' => '1', 'size' => 'm'],
            ['product_id' => '2', 'size' => 'm'],
            ['product_id' => '3', 'size' => 'm'],
            ['product_id' => '4', 'size' => 'm'],
            ['product_id' => '5', 'size' => 'm'],
            ['product_id' => '6', 'size' => 'm'],
            ['product_id' => '7', 'size' => 'm'],
            ['product_id' => '8', 'size' => 'm'],
            ['product_id' => '9', 'size' => 'm'],
            ['product_id' => '11', 'size' => 'm'],
            ['product_id' => '11', 'size' => 'm'],
            ['product_id' => '12', 'size' => 'm'],
            ['product_id' => '13', 'size' => 'm'],
            ['product_id' => '14', 'size' => 'm'],
            ['product_id' => '15', 'size' => 'm'],
            ['product_id' => '16', 'size' => 'm'],
            ['product_id' => '17', 'size' => 'm'],
            ['product_id' => '18', 'size' => 'm'],
            ['product_id' => '19', 'size' => 'm'],
            ['product_id' => '20', 'size' => 'm'],
            ['product_id' => '1', 'size' => 'l'],
            ['product_id' => '2', 'size' => 'l'],
            ['product_id' => '3', 'size' => 'l'],
            ['product_id' => '4', 'size' => 'l'],
            ['product_id' => '5', 'size' => 'l'],
            ['product_id' => '6', 'size' => 'l'],
            ['product_id' => '7', 'size' => 'l'],
            ['product_id' => '8', 'size' => 'l'],
            ['product_id' => '9', 'size' => 'l'],
            ['product_id' => '11', 'size' => 'l'],
            ['product_id' => '11', 'size' => 'l'],
            ['product_id' => '12', 'size' => 'l'],
            ['product_id' => '13', 'size' => 'l'],
            ['product_id' => '14', 'size' => 'l'],
            ['product_id' => '15', 'size' => 'l'],
            ['product_id' => '16', 'size' => 'l'],
            ['product_id' => '17', 'size' => 'l'],
            ['product_id' => '18', 'size' => 'l'],
            ['product_id' => '19', 'size' => 'l'],
            ['product_id' => '20', 'size' => 'l'],
            ['product_id' => '1', 'size' => 'xl'],
            ['product_id' => '2', 'size' => 'xl'],
            ['product_id' => '3', 'size' => 'xl'],
            ['product_id' => '4', 'size' => 'xl'],
            ['product_id' => '5', 'size' => 'xl'],
            ['product_id' => '6', 'size' => 'xl'],
            ['product_id' => '7', 'size' => 'xl'],
            ['product_id' => '8', 'size' => 'xl'],
            ['product_id' => '9', 'size' => 'xl'],
            ['product_id' => '11', 'size' => 'xl'],
            ['product_id' => '11', 'size' => 'xl'],
            ['product_id' => '12', 'size' => 'xl'],
            ['product_id' => '13', 'size' => 'xl'],
            ['product_id' => '14', 'size' => 'xl'],
            ['product_id' => '15', 'size' => 'xl'],
            ['product_id' => '16', 'size' => 'xl'],
            ['product_id' => '17', 'size' => 'xl'],
            ['product_id' => '18', 'size' => 'xl'],
            ['product_id' => '19', 'size' => 'xl'],
            ['product_id' => '20', 'size' => 'xl'],
            ['product_id' => '1', 'size' => 'xxl'],
            ['product_id' => '2', 'size' => 'xxl'],
            ['product_id' => '3', 'size' => 'xxl'],
            ['product_id' => '4', 'size' => 'xxl'],
            ['product_id' => '5', 'size' => 'xxl'],
            ['product_id' => '6', 'size' => 'xxl'],
            ['product_id' => '7', 'size' => 'xxl'],
            ['product_id' => '8', 'size' => 'xxl'],
            ['product_id' => '9', 'size' => 'xxl'],
            ['product_id' => '11', 'size' => 'xxl'],
            ['product_id' => '11', 'size' => 'xxl'],
            ['product_id' => '12', 'size' => 'xxl'],
            ['product_id' => '13', 'size' => 'xxl'],
            ['product_id' => '14', 'size' => 'xxl'],
            ['product_id' => '15', 'size' => 'xxl'],
            ['product_id' => '16', 'size' => 'xxl'],
            ['product_id' => '17', 'size' => 'xxl'],
            ['product_id' => '18', 'size' => 'xxl'],
            ['product_id' => '19', 'size' => 'xxl'],
            ['product_id' => '20', 'size' => 'xxl'],
        ];
        DB::table('sizes')->delete();
        DB::table('sizes')->insert($sizes);
    }
}
